# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='create PBC in 2D RVE', kernelModule='Eq2D_PBC', kernelFunction='PBC_Eq_2D', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgGroupBox(name='GroupBox_1', p='DialogBox', text='Input the Model name', layout='0')
RsgLabel(p='GroupBox_1', text='Tip:USE this plugin after mesh in Assembly Module', useBoldFont=True)
RsgTextField(p='GroupBox_1', fieldType='String', ncols=12, labelText='Model name:', keyword='modelName', default='')
RsgVerticalAligner(name='VAligner_1', p='DialogBox', pl=0, pr=0, pt=0, pb=0)
RsgPickButton(p='VAligner_1', text='Select the Left Boundary Edge    :', keyword='Edge_L', prompt='Pick an entity', entitiesToPick='MDB_GEOMETRY|EDGES', numberToPick='ONE')
RsgPickButton(p='VAligner_1', text='Select the Right Boundary Edge  :', keyword='Edge_R', prompt='Pick an entity', entitiesToPick='MDB_GEOMETRY|EDGES', numberToPick='ONE')
RsgPickButton(p='VAligner_1', text='Select the Up Boundary Edge     :', keyword='Edge_U', prompt='Pick an entity', entitiesToPick='MDB_GEOMETRY|EDGES', numberToPick='ONE')
RsgPickButton(p='VAligner_1', text='Select the Down Boundary Edge :', keyword='Edge_D', prompt='Pick an entity', entitiesToPick='MDB_GEOMETRY|EDGES', numberToPick='ONE')
RsgGroupBox(name='GroupBox_2', p='DialogBox', text='You should know:', layout='0')
RsgLabel(p='GroupBox_2', text='The plugin will delete RPs ,then generate RP-1 and RP-2', useBoldFont=True)
RsgLabel(p='GroupBox_2', text='RP-1 will control the RVE Ux,x use U1 (the set name;Ctrl_P1)', useBoldFont=False)
RsgLabel(p='GroupBox_2', text='RP-1 will control the RVE Uy,x use U2 (the set name;Ctrl_P1)', useBoldFont=False)
RsgLabel(p='GroupBox_2', text='RP-2 will control the RVE Uy,y use U2 (the set name;Ctrl_P2)', useBoldFont=False)
RsgLabel(p='GroupBox_2', text='RP-1 will control the RVE Ux,y use U1 (the set name;Ctrl_P2)', useBoldFont=False)
RsgHorizontalFrame(name='HFrame_1', p='GroupBox_2', layout='0', pl=200, pr=0, pt=0, pb=0)
RsgLabel(p='HFrame_1', text='Author:Yongjun Song', useBoldFont=True)
dialogBox.show()